##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-screensaver
    - autoconf-archive
    - clang
    - gcc
    - git
    - libmatekbd
    - libnotify
    - libxss
    - make
    - mate-common
    - mate-desktop
    - mate-menus
    - mate-session-manager
    - systemd
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-screensaver
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gcc
    - git
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmatekbd-dev
    - libnotify-dev
    - libpam0g-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxext-dev
    - libxss-dev
    - libxt-dev
    - libxxf86vm-dev
    - make
    - mate-common
    - x11proto-scrnsaver-dev
    - x11proto-xext-dev
    - x11proto-xf86vidmode-dev
    - xmlto

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-screensaver.git
    - autoconf-archive
    - clang
    - clang-analyzer
    - cppcheck-htmlreport
    - dbus-glib-devel
    - desktop-file-utils
    - gcc
    - git
    - gtk3-devel
    - libX11-devel
    - libXScrnSaver-devel
    - libXinerama-devel
    - libXmu-devel
    - libXtst-devel
    - libXxf86vm-devel
    - libmatekbd-devel
    - libnotify-devel
    - make
    - mate-common
    - mate-desktop-devel
    - mate-menus-devel
    - mesa-libGL-devel
    - pam-devel
    - redhat-rpm-config
    - systemd-devel
    - xmlto
    - xorg-x11-proto-devel

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - libdbus-glib-1-dev
    - libdconf-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libmate-menu-dev
    - libmatekbd-dev
    - libnotify-dev
    - libpam0g-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxext-dev
    - libxss-dev
    - libxt-dev
    - libxxf86vm-dev
    - make
    - mate-common
    - x11proto-scrnsaver-dev
    - x11proto-xext-dev
    - x11proto-xf86vidmode-dev
    - xmlto

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --enable-compile-warnings=maximum
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20
  - fi
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-screensaver-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

