#!/bin/bash

# fill it
pkgname=mate-screensaver
pkgver=2011.11.06
pkgrel=1
pkgdesc='Screensaver for MATE'
depends=('gtk2' 'dbus' 'mate-conf' 'mate-desktop' 'mate-menus')
makedepends=('pkgconfig' 'intltool' 'mate-doc-utils')
# editar esta funcion!
build() {
	cd $pkgsrc
	# obtener el archivo de github
	wget -c https://github.com/perberos/${pkgname}/tarball/${pkgver}
	
	# descomprimir
	tar xvzf ${pkgver}
	# entramos a la carpeta
	cd *-${pkgname}-*

	./autogen.sh \
		--prefix=/usr --sysconfdir=/etc \
		--mandir=/usr/share \
		--disable-static \
		--with-xscreensaverdir=/usr/share/xscreensaver/config \
		--with-xscreensaverhackdir=/usr/lib/xscreensaver \
		--with-mit-ext \
		--libexecdir=/usr/lib/${pkgname} || return 1

	make || return 1
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1

	install -m644 "${srcdir}/mate-screensaver.pam" "${pkgdir}/etc/pam.d/mate-screensaver"
	
	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
