.\" mate-screensaver-preferences manual page
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH MATE-SCREENSAVER-PREFERENCES 1 "13 February 2014" "MATE Desktop Environment"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
mate-screensaver-preferences \- Configure MATE Screensaver
.SH SYNOPSIS
.B mate-screensaver-preferences [ OPTIONS]
.SH DESCRIPTION
Manages preferences for the MATE Screensaver.
.SH OPTIONS
This program only accepts the standard GTK options.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/mate-desktop/mate-screensaver/issues
.SH "AUTHORS"
.SS mate-screensaver is maintained by:
.nf
Perberos <perberos@gmail.com>
Steve Zesch <stevezesch2@gmail.com>
Stefano Karapetsas <stefano@karapetsas.com>
.fi
.SS This manual page was originally written by:
Sven Arvidsson <sa@whiz.se> (2007)
.SS It has been updated for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "HISTORY"
.SS gnome-screensaver was written by William Jon McCann <mccann@jhu.edu>
.SH "SEE ALSO"
.SS The documentation available through the program's menu.
Further information may also be available at: http://wiki.mate-desktop.org/docs
.P
.BR mate-screensaver (1),
.BR mate-screensaver-command (1),
.BR gtk-options (7)
